### ISSUE TITLE
ICCV2023 paper: SA-BEV: Generating Semantic-Aware Bird's-Eye-View Feature for Multi-view 3D Object Detection

### ISSUE THREAD

**Issue by mengtan00** [autodriving-heart/ICCV2023-Papers-autonomous-driving#1]
Hi, our paper is accepted by ICCV 2023. Could you please show it in this repo?
Title: SA-BEV: Generating Semantic-Aware Bird's-Eye-View Feature for Multi-view 3D Object Detection
Paper: https://arxiv.org/abs/2307.11477
Code: https://github.com/mengtan00/SA-BEV
Keywords: 3d object detection
Thanks a lot!

**Comment by loki369loki** [comment]
> Hi, our paper is accepted by ICCV 2023. Could you please show it in this repo? Title: SA-BEV: Generating Semantic-Aware Bird's-Eye-View Feature for Multi-view 3D Object Detection Paper: https://arxiv.org/abs/2307.11477 Code: https://github.com/mengtan00/SA-BEV Keywords: 3d object detection Thanks a lot!

OK and so sorry for the late reply.
