### ISSUE TITLE
ICCV 2023 paper: CORE: Cooperative Reconstruction for Multi-Agent Perception

### ISSUE THREAD

**Issue by zllxot** [autodriving-heart/ICCV2023-Papers-autonomous-driving#2]
Hello, our paper has been accepted at ICCV 2023. Could you kindly consider featuring it in this repository?

Title: CORE: Cooperative Reconstruction for Multi-Agent Perception
Paper: https://arxiv.org/abs/2307.11514
Code: https://github.com/zllxot/CORE
Keywords: collaborative perception

Thank you!

**Comment by autodriving-heart** [comment]
> 

Hello, I have included your excellent work in the repository. Thanks for contributing to the repository.
